import { Info } from "lucide-react";
import { cn } from "@/lib/utils";

/** Canonical responsible-AI disclaimer required on results/analysis output. */
export const RESPONSIBLE_AI_MESSAGE =
  "This analysis is generated by AI and may contain mistakes. It should be used as career guidance, not as a final hiring decision or professional certification.";

interface ResponsibleAiNoticeProps {
  message?: string;
  className?: string;
}

export function ResponsibleAiNotice({
  message = RESPONSIBLE_AI_MESSAGE,
  className,
}: ResponsibleAiNoticeProps) {
  return (
    <div
      className={cn(
        "flex gap-3 rounded-card-sm border border-ai/20 bg-ai/5 p-4 text-sm text-muted",
        className,
      )}
    >
      <Info className="mt-0.5 h-5 w-5 shrink-0 text-ai" aria-hidden="true" />
      <p>
        <span className="font-semibold text-ink">Responsible AI notice. </span>
        {message}
      </p>
    </div>
  );
}
